spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      file-size-threshold: 2MB

ifc:
  storage:
    base-path: ./ifc-storage
  converter:
    url: http://localhost:3001
